name: flutter_form_builder
description: "A Flutter package to help you build forms with ease, providing validation, input fields, and more."
version: 1.0.0
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_doc_scanner: ^0.0.16
  flutter_svg: ^2.2.0
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  keyboard_actions: ^4.2.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/